#!/usr/bin/env bash
# Convert fat ffmpeg_kit_flutter_new frameworks to xcframeworks with
# separate iOS-device and iOS-simulator slices.
#
# The upstream fat frameworks only ship iOS-device slices. On Apple
# Silicon the iOS simulator runs as arm64; Xcode 14+ refuses to link a
# framework whose arm64 slice is tagged "ios" when targeting
# "ios-simulator". We add an arm64 simulator slice by vtool-rebasing
# the existing arm64 device slice to platform IOSSIMULATOR and pair it
# with the already-present x86_64 simulator slice.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_IOS="$(cd "${SCRIPT_DIR}/../ios" && pwd)"
SRC="${PKG_IOS}/Frameworks"
DST="${PKG_IOS}/FrameworksXc"

rm -rf "$DST"
mkdir -p "$DST"

shopt -s nullglob
for fw_dir in "$SRC"/*.framework; do
  fw_name=$(basename "$fw_dir" .framework)
  bin="$fw_dir/$fw_name"
  [ -f "$bin" ] || continue
  echo "=== $fw_name ==="

  out="$DST/$fw_name.xcframework"
  rm -rf "$out"
  mkdir -p "$out"

  # Device slice: keep both arm64 + arm64e from the original fat. Apple
  # dropped arm64e from the default iOS app target arch list, but we
  # preserve it so any future build setting (or downstream library that
  # still asks for it) keeps linking.
  dev_dir="$out/ios-arm64"
  mkdir -p "$dev_dir/$fw_name.framework"
  cp "$fw_dir/Info.plist" "$dev_dir/$fw_name.framework/"
  lipo -thin arm64 "$bin" -output "/tmp/${fw_name}_dev_arm64.bin" 2>/dev/null || true
  lipo -thin arm64e "$bin" -output "/tmp/${fw_name}_dev_arm64e.bin" 2>/dev/null || true
  dev_inputs=()
  [ -f "/tmp/${fw_name}_dev_arm64.bin" ] && dev_inputs+=("/tmp/${fw_name}_dev_arm64.bin")
  [ -f "/tmp/${fw_name}_dev_arm64e.bin" ] && dev_inputs+=("/tmp/${fw_name}_dev_arm64e.bin")
  if [ ${#dev_inputs[@]} -gt 0 ]; then
    lipo -create "${dev_inputs[@]}" -output "$dev_dir/$fw_name.framework/$fw_name"
  else
    cp "$bin" "$dev_dir/$fw_name.framework/$fw_name"
  fi
  if [ -d "$fw_dir/Headers" ]; then
    cp -R "$fw_dir/Headers" "$dev_dir/$fw_name.framework/"
  fi
  if [ -d "$fw_dir/Modules" ]; then
    cp -R "$fw_dir/Modules" "$dev_dir/$fw_name.framework/"
  fi
  # Re-sign with ad-hoc signature (so Xcode accepts)
  codesign --force --sign - "$dev_dir/$fw_name.framework" 2>/dev/null || true

  # Simulator slice: vtool'd arm64 + original x86_64 (both platform IOSSIMULATOR)
  sim_dir="$out/ios-arm64_x86_64-simulator"
  mkdir -p "$sim_dir/$fw_name.framework"
  cp "$fw_dir/Info.plist" "$sim_dir/$fw_name.framework/"
  if [ -d "$fw_dir/Headers" ]; then
    cp -R "$fw_dir/Headers" "$sim_dir/$fw_name.framework/"
  fi
  if [ -d "$fw_dir/Modules" ]; then
    cp -R "$fw_dir/Modules" "$sim_dir/$fw_name.framework/"
  fi

  arm64_tmp="/tmp/${fw_name}_arm64.bin"
  arm64_sim_tmp="/tmp/${fw_name}_arm64_sim.bin"
  lipo -thin arm64 "$bin" -output "$arm64_tmp"
  if ! vtool -arch arm64 -set-build-version 7 14.0 18.5 -replace -output "$arm64_sim_tmp" "$arm64_tmp" 2>/dev/null; then
    echo "vtool failed for $fw_name, trying minos 12.1"
    vtool -arch arm64 -set-build-version 7 12.1 18.5 -replace -output "$arm64_sim_tmp" "$arm64_tmp"
  fi
  lipo -thin x86_64 "$bin" -output "/tmp/${fw_name}_x86_64.bin" 2>/dev/null || true
  if [ -f "/tmp/${fw_name}_x86_64.bin" ]; then
    lipo -create "$arm64_sim_tmp" "/tmp/${fw_name}_x86_64.bin" -output "$sim_dir/$fw_name.framework/$fw_name"
  else
    cp "$arm64_sim_tmp" "$sim_dir/$fw_name.framework/$fw_name"
  fi
  codesign --force --sign - "$sim_dir/$fw_name.framework" 2>/dev/null || true
done

# xcframework Info.plist is generated by xcodebuild; use it to assemble
shopt -s nullglob
for xcf in "$DST"/*.xcframework; do
  name=$(basename "$xcf" .xcframework)
  echo "=== $name ==="
  cat > "$xcf/Info.plist" <<XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>AvailableLibraries</key>
  <array>
    <dict>
      <key>LibraryIdentifier</key>
      <string>ios-arm64</string>
      <key>LibraryPath</key>
      <string>$name.framework</string>
      <key>SupportedArchitectures</key>
      <array><string>arm64</string><string>arm64e</string></array>
      <key>SupportedPlatform</key>
      <string>ios</string>
    </dict>
    <dict>
      <key>LibraryIdentifier</key>
      <string>ios-arm64_x86_64-simulator</string>
      <key>LibraryPath</key>
      <string>$name.framework</string>
      <key>SupportedArchitectures</key>
      <array><string>arm64</string><string>x86_64</string></array>
      <key>SupportedPlatform</key>
      <string>ios</string>
      <key>SupportedPlatformVariant</key>
      <string>simulator</string>
    </dict>
  </array>
  <key>CFBundlePackageType</key>
  <string>XFWK</string>
  <key>XCFrameworkFormatVersion</key>
  <string>1.0</string>
  <key>XCFrameworkBundleVersionHash</key>
  <string>$(shasum -a 256 "$xcf/ios-arm64/$name.framework/$name" | head -c 16)</string>
  <key>XCFrameworkBundleVersion</key>
  <string>1.0</string>
  <key>XCFrameworkBundleShortVersionString</key>
  <string>1.0</string>
</dict>
</plist>
XML
done

ls -la "$DST"
